// Generated by scripts/generate.py; DO NOT EDIT.

export type Configuration = { schema_version: string; listen_address: string; policy_source: string; request_timeout_ms: number; fail_closed: boolean; api_key: string; extensions?: Record<string, unknown>; };

export type Decision = { schema_version: string; id: string; outcome: "allow" | "deny" | "transform" | "require_approval"; policy_revision: string; operation_digest: string; reason_codes: Array<string>; obligations: Array<Obligation>; evaluated_at: string; external_facts_digest: string; extensions?: Record<string, unknown>; };

export type Destination = { schema_version: string; id: string; kind: string; uri: string; region?: string; handling?: { retention_allowed?: boolean; training_allowed?: boolean; }; extensions?: Record<string, unknown>; };

export type ErrorEnvelope = { schema_version: string; request_id: string; code: "ng.validation.invalid_input" | "ng.authentication.unauthenticated" | "ng.policy.unavailable" | "ng.enforcement.denied" | "ng.storage.unavailable" | "ng.upstream.unavailable" | "ng.internal.failure"; message: string; extensions?: Record<string, unknown>; };

export type EventEnvelope = { schema_version: string; id: string; occurred_at: string; principal: Principal; operation: Operation; context: { session_id?: string; workflow_id?: string; trace_id?: string; application_id: string; environment: string; delegation_id?: string; }; external_facts: Array<ExternalFact>; transport?: { request_id?: string; received_at?: string; }; extensions?: Record<string, unknown>; };

export type ExternalFact = { schema_version: string; id: string; source: string; revision: string; value_ref: string; value_digest: string; resolved_at: string; expires_at: string; extensions?: Record<string, unknown>; };

export type Obligation = { schema_version: string; id: string; kind: "remove_paths" | "retain_paths" | "tokenize" | "mask" | "cap_records" | "cap_bytes" | "restrict_destination" | "require_confirmation" | "require_approval" | "prohibit_retention" | "response_check"; paths?: Array<string>; limit?: number; destination_id?: string; reviewer_group?: string; check_ref?: string; extensions?: Record<string, unknown>; };

export type Operation = { schema_version: string; id: string; kind: "model.invoke" | "retrieval.query" | "tool.call" | "response.emit" | "memory.read" | "memory.write" | "memory.update" | "memory.delete"; name: string; arguments_digest: string; data_refs: Array<string>; resources: Array<Resource>; destination: Destination; classifications: Array<string>; purpose: string; extensions?: Record<string, unknown>; };

export type Permit = { schema_version: string; id: string; principal_id: string; tenant_id: string; destination_id: string; classifications: Array<string>; purpose: string; operation_digest: string; policy_revision: string; external_facts_digest: string; obligations_digest: string; nonce: string; issued_at: string; expires_at: string; key_id: string; signature: string; extensions?: Record<string, unknown>; };

export type PolicyManifest = { schema_version: string; id: string; version: string; minimum_core_version: string; namespaces: Array<string>; dependencies: Array<string>; external_fact_sources: Array<string>; source_digest: string; build_digest: string; signing_identity: string; created_at: string; extensions?: Record<string, unknown>; };

export type Principal = { schema_version: string; id: string; tenant_id: string; kind: "user" | "service" | "workload" | "agent"; roles: Array<string>; claim_refs?: Array<string>; extensions?: Record<string, unknown>; };

export type Receipt = { schema_version: string; id: string; tenant_id: string; decision: Decision; policy_revision: string; event_digest: string; configuration_digest: string; external_facts_digest: string; input_ref: string; enforcement_outcome: "not_executed" | "succeeded" | "failed" | "cancelled"; recorded_at: string; previous_digest: string; receipt_digest: string; extensions?: Record<string, unknown>; };

export type Resource = { schema_version: string; id: string; kind: string; tenant_id: string; classifications: Array<string>; data_refs?: Array<string>; extensions?: Record<string, unknown>; };

export type TestCase = { schema_version: string; id: string; description: string; event: EventEnvelope; expected_decision: Decision; extensions?: Record<string, unknown>; };
