# Generated by scripts/generate.py; DO NOT EDIT.
from __future__ import annotations
from typing import Literal, NotRequired, TypedDict

class Configuration(TypedDict):
    schema_version: str
    listen_address: str
    policy_source: str
    request_timeout_ms: int
    fail_closed: bool
    api_key: str
    extensions: NotRequired[dict[str, object]]

class Decision(TypedDict):
    schema_version: str
    id: str
    outcome: Literal["allow", "deny", "transform", "require_approval"]
    policy_revision: str
    operation_digest: str
    reason_codes: list[str]
    obligations: list[Obligation]
    evaluated_at: str
    external_facts_digest: str
    extensions: NotRequired[dict[str, object]]

class DestinationHandling(TypedDict):
    retention_allowed: NotRequired[bool]
    training_allowed: NotRequired[bool]

class Destination(TypedDict):
    schema_version: str
    id: str
    kind: str
    uri: str
    region: NotRequired[str]
    handling: NotRequired[DestinationHandling]
    extensions: NotRequired[dict[str, object]]

class ErrorEnvelope(TypedDict):
    schema_version: str
    request_id: str
    code: Literal["ng.validation.invalid_input", "ng.authentication.unauthenticated", "ng.policy.unavailable", "ng.enforcement.denied", "ng.storage.unavailable", "ng.upstream.unavailable", "ng.internal.failure"]
    message: str
    extensions: NotRequired[dict[str, object]]

class EventEnvelopeContext(TypedDict):
    session_id: NotRequired[str]
    workflow_id: NotRequired[str]
    trace_id: NotRequired[str]
    application_id: str
    environment: str
    delegation_id: NotRequired[str]

class EventEnvelopeTransport(TypedDict):
    request_id: NotRequired[str]
    received_at: NotRequired[str]

class EventEnvelope(TypedDict):
    schema_version: str
    id: str
    occurred_at: str
    principal: Principal
    operation: Operation
    context: EventEnvelopeContext
    external_facts: list[ExternalFact]
    transport: NotRequired[EventEnvelopeTransport]
    extensions: NotRequired[dict[str, object]]

class ExternalFact(TypedDict):
    schema_version: str
    id: str
    source: str
    revision: str
    value_ref: str
    value_digest: str
    resolved_at: str
    expires_at: str
    extensions: NotRequired[dict[str, object]]

class Obligation(TypedDict):
    schema_version: str
    id: str
    kind: Literal["remove_paths", "retain_paths", "tokenize", "mask", "cap_records", "cap_bytes", "restrict_destination", "require_confirmation", "require_approval", "prohibit_retention", "response_check"]
    paths: NotRequired[list[str]]
    limit: NotRequired[int]
    destination_id: NotRequired[str]
    reviewer_group: NotRequired[str]
    check_ref: NotRequired[str]
    extensions: NotRequired[dict[str, object]]

class Operation(TypedDict):
    schema_version: str
    id: str
    kind: Literal["model.invoke", "retrieval.query", "tool.call", "response.emit", "memory.read", "memory.write", "memory.update", "memory.delete"]
    name: str
    arguments_digest: str
    data_refs: list[str]
    resources: list[Resource]
    destination: Destination
    classifications: list[str]
    purpose: str
    extensions: NotRequired[dict[str, object]]

class Permit(TypedDict):
    schema_version: str
    id: str
    principal_id: str
    tenant_id: str
    destination_id: str
    classifications: list[str]
    purpose: str
    operation_digest: str
    policy_revision: str
    external_facts_digest: str
    obligations_digest: str
    nonce: str
    issued_at: str
    expires_at: str
    key_id: str
    signature: str
    extensions: NotRequired[dict[str, object]]

class PolicyManifest(TypedDict):
    schema_version: str
    id: str
    version: str
    minimum_core_version: str
    namespaces: list[str]
    dependencies: list[str]
    external_fact_sources: list[str]
    source_digest: str
    build_digest: str
    signing_identity: str
    created_at: str
    extensions: NotRequired[dict[str, object]]

class Principal(TypedDict):
    schema_version: str
    id: str
    tenant_id: str
    kind: Literal["user", "service", "workload", "agent"]
    roles: list[str]
    claim_refs: NotRequired[list[str]]
    extensions: NotRequired[dict[str, object]]

class Receipt(TypedDict):
    schema_version: str
    id: str
    tenant_id: str
    decision: Decision
    policy_revision: str
    event_digest: str
    configuration_digest: str
    external_facts_digest: str
    input_ref: str
    enforcement_outcome: Literal["not_executed", "succeeded", "failed", "cancelled"]
    recorded_at: str
    previous_digest: str
    receipt_digest: str
    extensions: NotRequired[dict[str, object]]

class Resource(TypedDict):
    schema_version: str
    id: str
    kind: str
    tenant_id: str
    classifications: list[str]
    data_refs: NotRequired[list[str]]
    extensions: NotRequired[dict[str, object]]

class TestCase(TypedDict):
    schema_version: str
    id: str
    description: str
    event: EventEnvelope
    expected_decision: Decision
    extensions: NotRequired[dict[str, object]]
