// Code generated by scripts/generate.py; DO NOT EDIT.
package v1

type Configuration struct {
	SchemaVersion    string          `json:"schema_version"`
	ListenAddress    string          `json:"listen_address"`
	PolicySource     string          `json:"policy_source"`
	RequestTimeoutMs int64           `json:"request_timeout_ms"`
	FailClosed       bool            `json:"fail_closed"`
	ApiKey           string          `json:"api_key"`
	Extensions       *map[string]any `json:"extensions,omitempty"`
}

type Decision struct {
	SchemaVersion       string          `json:"schema_version"`
	Id                  string          `json:"id"`
	Outcome             string          `json:"outcome"`
	PolicyRevision      string          `json:"policy_revision"`
	OperationDigest     string          `json:"operation_digest"`
	ReasonCodes         []string        `json:"reason_codes"`
	Obligations         []Obligation    `json:"obligations"`
	EvaluatedAt         string          `json:"evaluated_at"`
	ExternalFactsDigest string          `json:"external_facts_digest"`
	Extensions          *map[string]any `json:"extensions,omitempty"`
}

type Destination struct {
	SchemaVersion string  `json:"schema_version"`
	Id            string  `json:"id"`
	Kind          string  `json:"kind"`
	Uri           string  `json:"uri"`
	Region        *string `json:"region,omitempty"`
	Handling      *struct {
		RetentionAllowed *bool `json:"retention_allowed,omitempty"`
		TrainingAllowed  *bool `json:"training_allowed,omitempty"`
	} `json:"handling,omitempty"`
	Extensions *map[string]any `json:"extensions,omitempty"`
}

type ErrorEnvelope struct {
	SchemaVersion string          `json:"schema_version"`
	RequestId     string          `json:"request_id"`
	Code          string          `json:"code"`
	Message       string          `json:"message"`
	Extensions    *map[string]any `json:"extensions,omitempty"`
}

type EventEnvelope struct {
	SchemaVersion string    `json:"schema_version"`
	Id            string    `json:"id"`
	OccurredAt    string    `json:"occurred_at"`
	Principal     Principal `json:"principal"`
	Operation     Operation `json:"operation"`
	Context       struct {
		SessionId     *string `json:"session_id,omitempty"`
		WorkflowId    *string `json:"workflow_id,omitempty"`
		TraceId       *string `json:"trace_id,omitempty"`
		ApplicationId string  `json:"application_id"`
		Environment   string  `json:"environment"`
		DelegationId  *string `json:"delegation_id,omitempty"`
	} `json:"context"`
	ExternalFacts []ExternalFact `json:"external_facts"`
	Transport     *struct {
		RequestId  *string `json:"request_id,omitempty"`
		ReceivedAt *string `json:"received_at,omitempty"`
	} `json:"transport,omitempty"`
	Extensions *map[string]any `json:"extensions,omitempty"`
}

type ExternalFact struct {
	SchemaVersion string          `json:"schema_version"`
	Id            string          `json:"id"`
	Source        string          `json:"source"`
	Revision      string          `json:"revision"`
	ValueRef      string          `json:"value_ref"`
	ValueDigest   string          `json:"value_digest"`
	ResolvedAt    string          `json:"resolved_at"`
	ExpiresAt     string          `json:"expires_at"`
	Extensions    *map[string]any `json:"extensions,omitempty"`
}

type Obligation struct {
	SchemaVersion string          `json:"schema_version"`
	Id            string          `json:"id"`
	Kind          string          `json:"kind"`
	Paths         *[]string       `json:"paths,omitempty"`
	Limit         *int64          `json:"limit,omitempty"`
	DestinationId *string         `json:"destination_id,omitempty"`
	ReviewerGroup *string         `json:"reviewer_group,omitempty"`
	CheckRef      *string         `json:"check_ref,omitempty"`
	Extensions    *map[string]any `json:"extensions,omitempty"`
}

type Operation struct {
	SchemaVersion   string          `json:"schema_version"`
	Id              string          `json:"id"`
	Kind            string          `json:"kind"`
	Name            string          `json:"name"`
	ArgumentsDigest string          `json:"arguments_digest"`
	DataRefs        []string        `json:"data_refs"`
	Resources       []Resource      `json:"resources"`
	Destination     Destination     `json:"destination"`
	Classifications []string        `json:"classifications"`
	Purpose         string          `json:"purpose"`
	Extensions      *map[string]any `json:"extensions,omitempty"`
}

type Permit struct {
	SchemaVersion       string          `json:"schema_version"`
	Id                  string          `json:"id"`
	PrincipalId         string          `json:"principal_id"`
	TenantId            string          `json:"tenant_id"`
	DestinationId       string          `json:"destination_id"`
	Classifications     []string        `json:"classifications"`
	Purpose             string          `json:"purpose"`
	OperationDigest     string          `json:"operation_digest"`
	PolicyRevision      string          `json:"policy_revision"`
	ExternalFactsDigest string          `json:"external_facts_digest"`
	ObligationsDigest   string          `json:"obligations_digest"`
	Nonce               string          `json:"nonce"`
	IssuedAt            string          `json:"issued_at"`
	ExpiresAt           string          `json:"expires_at"`
	KeyId               string          `json:"key_id"`
	Signature           string          `json:"signature"`
	Extensions          *map[string]any `json:"extensions,omitempty"`
}

type PolicyManifest struct {
	SchemaVersion       string          `json:"schema_version"`
	Id                  string          `json:"id"`
	Version             string          `json:"version"`
	MinimumCoreVersion  string          `json:"minimum_core_version"`
	Namespaces          []string        `json:"namespaces"`
	Dependencies        []string        `json:"dependencies"`
	ExternalFactSources []string        `json:"external_fact_sources"`
	SourceDigest        string          `json:"source_digest"`
	BuildDigest         string          `json:"build_digest"`
	SigningIdentity     string          `json:"signing_identity"`
	CreatedAt           string          `json:"created_at"`
	Extensions          *map[string]any `json:"extensions,omitempty"`
}

type Principal struct {
	SchemaVersion string          `json:"schema_version"`
	Id            string          `json:"id"`
	TenantId      string          `json:"tenant_id"`
	Kind          string          `json:"kind"`
	Roles         []string        `json:"roles"`
	ClaimRefs     *[]string       `json:"claim_refs,omitempty"`
	Extensions    *map[string]any `json:"extensions,omitempty"`
}

type Receipt struct {
	SchemaVersion       string          `json:"schema_version"`
	Id                  string          `json:"id"`
	TenantId            string          `json:"tenant_id"`
	Decision            Decision        `json:"decision"`
	PolicyRevision      string          `json:"policy_revision"`
	EventDigest         string          `json:"event_digest"`
	ConfigurationDigest string          `json:"configuration_digest"`
	ExternalFactsDigest string          `json:"external_facts_digest"`
	InputRef            string          `json:"input_ref"`
	EnforcementOutcome  string          `json:"enforcement_outcome"`
	RecordedAt          string          `json:"recorded_at"`
	PreviousDigest      string          `json:"previous_digest"`
	ReceiptDigest       string          `json:"receipt_digest"`
	Extensions          *map[string]any `json:"extensions,omitempty"`
}

type Resource struct {
	SchemaVersion   string          `json:"schema_version"`
	Id              string          `json:"id"`
	Kind            string          `json:"kind"`
	TenantId        string          `json:"tenant_id"`
	Classifications []string        `json:"classifications"`
	DataRefs        *[]string       `json:"data_refs,omitempty"`
	Extensions      *map[string]any `json:"extensions,omitempty"`
}

type TestCase struct {
	SchemaVersion    string          `json:"schema_version"`
	Id               string          `json:"id"`
	Description      string          `json:"description"`
	Event            EventEnvelope   `json:"event"`
	ExpectedDecision Decision        `json:"expected_decision"`
	Extensions       *map[string]any `json:"extensions,omitempty"`
}
