#!/usr/bin/env python3
"""Generate transport types and OpenAPI from the committed JSON Schemas (NG-F003).

Runtime validation remains schema-based; language types alone are not validators.
This deliberately small generator supports the schema constructs used by this repo.
"""
import argparse
import json
import os
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]


def name(value):
    return "".join(part.title() for part in value.replace("_", "-").split("-"))


def ref_name(value):
    return name(value.removesuffix(".schema.json"))


def field_type(schema, language):
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "enum" in schema and language != "go":
        values = ", ".join(json.dumps(v) for v in schema["enum"])
        return f"Literal[{values}]" if language == "py" else " | ".join(json.dumps(v) for v in schema["enum"])
    kind = schema.get("type")
    primitives = {"string": ("string", "str", "string"), "integer": ("int64", "int", "number"), "boolean": ("bool", "bool", "boolean")}
    if kind in primitives:
        return primitives[kind][["go", "py", "ts"].index(language)]
    if kind == "array":
        item = field_type(schema["items"], language)
        return {"go": f"[]{item}", "py": f"list[{item}]", "ts": f"Array<{item}>"}[language]
    if kind == "object":
        if "properties" in schema:
            if language == "py":
                # Anonymous nested records get named definitions in the main pass.
                return schema["x-generated-name"]
            fields = []
            for key, value in schema["properties"].items():
                required = key in schema.get("required", [])
                typ = field_type(value, language)
                if language == "go":
                    fields.append(f'{name(key)} {typ if required else "*" + typ} `json:"{key}{"" if required else ",omitempty"}"`')
                else:
                    fields.append(f'{key}{"" if required else "?"}: {typ};')
            return ("struct {\n" + "\n".join(fields) + "\n}") if language == "go" else ("{ " + " ".join(fields) + " }")
        return {"go": "map[string]any", "py": "dict[str, object]", "ts": "Record<string, unknown>"}[language]
    raise ValueError(f"unsupported generated schema type: {schema}")


def generate():
    schemas = {p.stem.removesuffix(".schema"): json.loads(p.read_text()) for p in sorted((ROOT / "schemas/v1").glob("*.schema.json"))}
    go = ["// Code generated by scripts/generate.py; DO NOT EDIT.\npackage v1\n"]
    py = ['# Generated by scripts/generate.py; DO NOT EDIT.', 'from __future__ import annotations', 'from typing import Literal, NotRequired, TypedDict', '']
    ts = ['// Generated by scripts/generate.py; DO NOT EDIT.\n']

    def python_record(title, schema):
        for key, value in schema["properties"].items():
            if value.get("type") == "object" and "properties" in value:
                value["x-generated-name"] = title + name(key)
                python_record(value["x-generated-name"], value)
        py.append(f"class {title}(TypedDict):")
        for key, value in schema["properties"].items():
            typ = field_type(value, "py")
            py.append(f'    {key}: {typ if key in schema["required"] else "NotRequired[" + typ + "]"}')
        py.append("")

    for schema in schemas.values():
        title = schema["title"]
        go.append(f'type {title} ' + field_type(schema, "go") + "\n")
        ts.append(f'export type {title} = ' + field_type(schema, "ts") + ";\n")
        python_record(title, schema)
    go_bytes = subprocess.run([os.environ.get("GOFMT", "gofmt")], input="\n".join(go).encode(), check=True, capture_output=True).stdout
    # Re-read to avoid authoring helper annotations leaking into OpenAPI.
    def component(value):
        if isinstance(value, list):
            return [component(v) for v in value]
        if not isinstance(value, dict):
            return value
        return {k: ("#/components/schemas/" + ref_name(v) if k == "$ref" else component(v)) for k, v in value.items() if k not in ("$id", "$schema")}
    components = {s["title"]: component(s) for p in sorted((ROOT / "schemas/v1").glob("*.schema.json")) for s in [json.loads(p.read_text())]}
    spec = {"openapi": "3.1.0", "info": {"title": "NormGate", "version": "0.1.0", "description": "Phase 1 contract components. Service routes are introduced in Phase 3."}, "jsonSchemaDialect": "https://json-schema.org/draft/2020-12/schema", "paths": {}, "components": {"schemas": components}}
    return {
        "internal/contracts/v1/types.gen.go": go_bytes,
        "sdk/python/src/normgate/types/__init__.py": ("\n".join(py).rstrip() + "\n").encode(),
        "sdk/typescript/src/types/index.ts": ("\n".join(ts).rstrip() + "\n").encode(),
        "api/openapi/openapi.gen.json": (json.dumps(spec, indent=2) + "\n").encode(),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for filename, data in generate().items():
        path = ROOT / filename
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                stale.append(filename)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    if stale:
        print("Generated artifacts are stale; run make generate:\n" + "\n".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
